// <auto-generated />
using System;
using Livros.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Livros.Dados.Migracoes
{
    [DbContext(typeof(ContextoLivros))]
    [Migration("20260907061625_CriarLivrosSimilares")]
    partial class CriarLivrosSimilares
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Livros.Dados.CategoriaResultado", b =>
                {
                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<int>("TotalLivros")
                        .HasColumnType("integer")
                        .HasColumnName("total_livros");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.Interacao", b =>
                {
                    b.Property<long>("IdInteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_interacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdInteracao"));

                    b.Property<DateTimeOffset>("DataInteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_interacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IdLivro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_livro");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoInteracao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_interacao");

                    b.HasKey("IdInteracao")
                        .HasName("pk_interacoes");

                    b.HasIndex("IdLivro")
                        .HasDatabaseName("ix_interacoes_id_livro");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_interacoes_id_usuario");

                    b.ToTable("interacoes", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("chk_tipo_interacao", "tipo_interacao IN ('visualizacao', 'salvou', 'removeu_salvo')");
                        });
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.Livro", b =>
                {
                    b.Property<long>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_livro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdLivro"));

                    b.Property<int?>("AnoPublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("ano_publicacao");

                    b.Property<string>("Autores")
                        .HasColumnType("text")
                        .HasColumnName("autores");

                    b.Property<decimal?>("AvaliacaoMedia")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("avaliacao_media");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Editora")
                        .HasColumnType("text")
                        .HasColumnName("editora");

                    b.Property<string>("ImagemCapa")
                        .HasColumnType("text")
                        .HasColumnName("imagem_capa");

                    b.Property<string>("Isbn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("isbn");

                    b.Property<string>("MesPublicacao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mes_publicacao");

                    b.Property<decimal?>("PrecoInicial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_inicial");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("IdLivro")
                        .HasName("pk_livros");

                    b.ToTable("livros", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.LivroSalvo", b =>
                {
                    b.Property<long>("IdSalvo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_salvo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdSalvo"));

                    b.Property<DateTimeOffset>("DataSalvo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_salvo")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IdLivro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_livro");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdSalvo")
                        .HasName("pk_livros_salvos");

                    b.HasIndex("IdLivro")
                        .HasDatabaseName("ix_livros_salvos_id_livro");

                    b.HasIndex("IdUsuario", "IdLivro")
                        .IsUnique()
                        .HasDatabaseName("uq_usuario_livro_salvo");

                    b.ToTable("livros_salvos", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.LivroSimilar", b =>
                {
                    b.Property<long>("IdLivro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_livro");

                    b.Property<short>("Posicao")
                        .HasColumnType("smallint")
                        .HasColumnName("posicao");

                    b.Property<long>("IdLivroSimilar")
                        .HasColumnType("bigint")
                        .HasColumnName("id_livro_similar");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("IdLivro", "Posicao")
                        .HasName("pk_livros_similares");

                    b.HasIndex("IdLivroSimilar")
                        .HasDatabaseName("ix_livros_similares_id_livro_similar");

                    b.ToTable("livros_similares", (string)null);
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdUsuario"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("usuarios_email_key");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.Interacao", b =>
                {
                    b.HasOne("Livros.Dominio.Entidades.Livro", "Livro")
                        .WithMany("Interacoes")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interacao_livro");

                    b.HasOne("Livros.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Interacoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interacao_usuario");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.LivroSalvo", b =>
                {
                    b.HasOne("Livros.Dominio.Entidades.Livro", "Livro")
                        .WithMany("LivrosSalvos")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salvo_livro");

                    b.HasOne("Livros.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("LivrosSalvos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salvo_usuario");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.LivroSimilar", b =>
                {
                    b.HasOne("Livros.Dominio.Entidades.Livro", "Livro")
                        .WithMany("Similares")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_livro");

                    b.HasOne("Livros.Dominio.Entidades.Livro", "Similar")
                        .WithMany()
                        .HasForeignKey("IdLivroSimilar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_similar_livro_alvo");

                    b.Navigation("Livro");

                    b.Navigation("Similar");
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.Livro", b =>
                {
                    b.Navigation("Interacoes");

                    b.Navigation("LivrosSalvos");

                    b.Navigation("Similares");
                });

            modelBuilder.Entity("Livros.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Interacoes");

                    b.Navigation("LivrosSalvos");
                });
#pragma warning restore 612, 618
        }
    }
}
